version: "3.8"
services:
  mysql:
    build: ./mysql
    container_name: mysql
    restart: always
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
      - ./mysql/test_db:/home
    ports:
        - "3306:3306"
    environment:
      MYSQL_DATABASE: sql_playground
      MYSQL_USER: sample
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
